### ISSUE TITLE
Missing MCP file for modules

### ISSUE THREAD

**Issue by tylerwillingham** [rsanchez/generator-ee-addon#1]
This prompt while creating a module isn't accurate as it stands:

```
[?] Does the module need an mcp file for control panel views or actions? No
```

EE requires an MCP file (even if the class is left empty). Took me a little debugging to find this one so I figured it would be worth mentioning incase anyone else runs into this.

**Comment by rsanchez** [comment]
I could've sworn it was not required to have an mcp file (maybe this has changed in EE?). What kind of error were you running into?

**Comment by tylerwillingham** [comment]
It fails silently :( maybe it used to not be required but it was failing for me in 2.7.2 and the current user guide shows it's a required file

**Comment by rsanchez** [comment]
I will look into it. Thanks for the report!

**Comment by tylerwillingham** [comment]
No problem. If I have the time I'll submit a pull request. I just wanted to post this before I forgot.

**Comment by tylerwillingham** [comment]
Woo!

**Comment by rsanchez** [comment]
BTW. This generator has been ported over to PHP as part of the [eecli](https://github.com/rsanchez/eecli) project. I am going to try and maintain both of these generators, but eecli will probably be more cutting edge. Not that I foresee huge changes with the addon generator going forward, however. Seems mostly feature complete.

**Comment by tylerwillingham** [comment]
Awesome, I like what I've seen with that so far. Thanks again Rob
